### ISSUE TITLE
Fonte do livro

### ISSUE THREAD

**Issue by suzanasalama** [hedra-editora/mi_trans_tatu#1]
@paulopompermaier Engraçado que essa fonte está como Libertine mas tá parecendo muito a Garamond! Será que tô doida? Dá uma olhada?

**Comment by paulopompermaier** [comment]
Está em Libertine sim...
Quando estou na dúvida, costumo comparar glifos bem específicos da fonte, como o til da Garamond e esse A em capitular que tem uma serifa mais pronunciada... 
Abaixo, o mesmo trecho, primeiro na Garamond, o segundo em Libertine:

![garamond](https://user-images.githubusercontent.com/78091918/162217334-c1f2b26c-060a-491b-b601-dd2c8331caf0.png)
![libertine](https://user-images.githubusercontent.com/78091918/162217338-54f9a43f-2f3a-42d3-a7de-851ded8ddf02.png)
